apiVersion: v1
kind: Service
metadata:
  name: k8s-prometheus-app-service
spec:
  selector:
    app: k8s-prometheus-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP